services:
  app:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: .docker/app_dockerfile
      target: production
    volumes:
      - ./logs:/logs
    restart: always
    environment:
      - VUE_APP_API_URL=http://titirici-datalab.ch.ic.ac.uk:5001
      - VUE_APP_LOGO_URL=https://images.squarespace-cdn.com/content/v1/5c619b5c523958463c9806fc/1586972125161-PJ57FS4GS3BHUCYOIL5V/logo%2Bresearch-01.png
      - VUE_APP_HOMEPAGE_URL=https://www.titiricigroup.com/
    ports:
      - "8081:8081"

  app_dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: .docker/app_dockerfile
      target: development
    volumes:
      - ./logs:/logs
      - ./webapp:/app
    ports:
      - "8081:8081"

  api:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: .docker/server_dockerfile
      target: production
      args:
        - WEB_CONCURRENCY=4
    depends_on:
      - database
    restart: always
    volumes:
      - ./logs:/logs
      - ./config.json:/app/config.json
      - ./.env:/app/.env
      - /data:/app/files
    ports:
      - "5001:5001"
    networks:
      - backend
    environment:
      - PYDATALAB_MONGO_URI=mongodb://database:27017/datalabvue

  api_dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: .docker/server_dockerfile
      target: development
    depends_on:
      - database
    volumes:
      - ./logs:/logs
      - ./pydatalab:/app
    ports:
      - "5001:5001"
    networks:
      - backend
    environment:
      - PYDATALAB_TESTING=true
      - PYDATALAB_MONGO_URI=mongodb://database:27017/datalabvue

  database:
    build:
      context: .
      dockerfile: .docker/mongo_dockerfile
    volumes:
      - ./logs:/var/logs/mongod
      - /data/db:/data/db
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"

networks:
  backend:
    driver: bridge
